# Generated by Django 2.0.13 on 2019-05-13 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0006_auto_20190513_1029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageinfo',
            name='info_id',
        ),
        migrations.AddField(
            model_name='imageinfo',
            name='name',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Data.Image', verbose_name='image name'),
        ),
        migrations.AddField(
            model_name='imageinfo',
            name='parents',
            field=models.CharField(blank=True, max_length=50, verbose_name='image parents'),
        ),
        migrations.AddField(
            model_name='imageinfo',
            name='parents_hash',
            field=models.CharField(blank=True, max_length=34, verbose_name='parents hash'),
        ),
        migrations.AddField(
            model_name='imageinfo',
            name='selfhash',
            field=models.CharField(default='', max_length=34, verbose_name='self hash'),
        ),
    ]
