# Generated by Django 2.0.13 on 2019-05-13 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0007_auto_20190513_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageinfo',
            name='bndbox_xmax',
            field=models.IntegerField(blank=True, default=0, verbose_name='bndbox xMax'),
        ),
        migrations.AddField(
            model_name='imageinfo',
            name='bndbox_xmin',
            field=models.IntegerField(blank=True, default=0, verbose_name='bndbox xMin'),
        ),
        migrations.AddField(
            model_name='imageinfo',
            name='bndbox_ymax',
            field=models.IntegerField(blank=True, default=0, verbose_name='bndbox yMax'),
        ),
        migrations.AddField(
            model_name='imageinfo',
            name='bndbox_ymin',
            field=models.IntegerField(blank=True, default=0, verbose_name='bndbox yMin'),
        ),
    ]
