# Generated by Django 5.2.17 on 2026-10-06 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0010_auto_20190513_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageinfo',
            name='color_space',
            field=models.CharField(choices=[('sRGB', 'sRGB'), ('AdobeRGB', 'AdobeRGB'), ('AppleRGB', 'AppleRGB'), ('ColorMatchRGB', 'ColorMatchRGB'), ('CMYK', 'CMYK'), ('YIQ', 'YIQ'), ('YUV|YCrCb', 'YUV|YCrCb'), ('HSV', 'HSV'), ('HSI|HSL', 'HSI|HSL'), ('L*a*b', 'L*a*b'), ('CIERGB', 'CIERGB'), ('CIELUV', 'CIELUV'), ('CIELAB', 'CIELAB'), ('CIE1931XYZ', 'CIE1931XYZ'), ('CIE1964UVW', 'CIE1964UVW')], default='sRGB', max_length=16, verbose_name='color space'),
        ),
    ]
