# Generated by Django 2.0.13 on 2019-05-11 04:46

import django.contrib.sites.managers
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import mdeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(upload_to='photo')),
                ('photo_name', models.CharField(default='', max_length=26, verbose_name='name')),
                ('photographer_name', models.CharField(max_length=100)),
                ('pub_date', models.DateField()),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.Site')),
            ],
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('on_site', django.contrib.sites.managers.CurrentSiteManager()),
            ],
        ),
        migrations.CreateModel(
            name='SiteSettingArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=26, verbose_name='title')),
                ('article_content', mdeditor.fields.MDTextField(default='', verbose_name='content')),
                ('article_create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='create time')),
                ('article_modify_time', models.DateTimeField(auto_now=True, verbose_name='modify time')),
            ],
            options={
                'verbose_name_plural': 'Site Setting Articles',
                'verbose_name': 'Site Setting Article',
            },
        ),
    ]
