# Generated by Django 2.0.13 on 2019-05-07 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='data_categories',
            field=models.IntegerField(default='UNCT', verbose_name='data categories'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='dataset_import_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='dataset import time'),
        ),
    ]
