# Generated by Django 2.0.13 on 2019-05-07 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0002_auto_20190507_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='data_categories',
            field=models.IntegerField(default=0, verbose_name='data categories'),
        ),
    ]
