# Generated by Django 2.0.13 on 2019-05-10 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0003_auto_20190507_1424'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dataset',
            options={'verbose_name': 'dataset', 'verbose_name_plural': 'datasets'},
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='data_categories',
        ),
        migrations.AddField(
            model_name='dataset',
            name='data_classes',
            field=models.IntegerField(default=0, verbose_name='data classes'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='dataset_address',
            field=models.CharField(max_length=100, verbose_name='dataset address'),
        ),
    ]
