# Generated by Django 2.0.13 on 2019-05-10 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0005_auto_20190510_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageinfo',
            name='annotation_file',
            field=models.CharField(default='', max_length=50, verbose_name='annotation file'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='dataset_category',
            field=models.CharField(choices=[('UNCT', 'uncategoried'), ('FACE', 'face recognize'), ('VEHI', 'vehicle recognize'), ('OBJ', 'object recognize')], default='UNCT', max_length=4, verbose_name='dataset category'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='test_file',
            field=models.CharField(default='test.txt', max_length=100, verbose_name='test label file'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='train_file',
            field=models.CharField(default='train.txt', max_length=100, verbose_name='train label file'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='val_file',
            field=models.CharField(default='val.txt', max_length=100, verbose_name='val label file'),
        ),
    ]
