# Generated by Django 2.0.13 on 2019-05-10 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0006_auto_20190510_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageinfo',
            name='image_depth',
        ),
        migrations.AddField(
            model_name='imageinfo',
            name='bndbox_xmax',
            field=models.IntegerField(default=models.IntegerField(default=1, verbose_name='image height'), verbose_name='bndbox yMax'),
        ),
        migrations.AddField(
            model_name='imageinfo',
            name='bndbox_xmin',
            field=models.IntegerField(default=1, verbose_name='bndbox xMin'),
        ),
        migrations.AddField(
            model_name='imageinfo',
            name='bndbox_ymin',
            field=models.IntegerField(default=1, verbose_name='bndbox yMin'),
        ),
        migrations.AddField(
            model_name='imageinfo',
            name='color_space',
            field=models.CharField(choices=[('sRGB', 'sRGB'), ('AdobeRGB', 'AdobeRGB'), ('AppleRGB', 'AppleRGB'), ('ColorMatchRGB', 'ColorMatchRGB'), ('CMYK', 'CMYK'), ('YIQ', 'YIQ'), ('YUV|YCrCb', 'YUV|YCrCb'), ('HSV', 'HSV'), ('HSI|HSL', 'HSI|HSL'), ('L*a*b', 'L*a*b'), ('CIERGB', 'CIERGB'), ('CIELUV', 'CIELUV'), ('CIELAB', 'CIELAB'), ('CIE1931XYZ', 'CIE1931XYZ'), ('CIE1964UVW', 'CIE1964UVW')], default='sRGB', max_length=10, verbose_name='color space'),
        ),
        migrations.AddField(
            model_name='imageinfo',
            name='image_height',
            field=models.IntegerField(default=1, verbose_name='image height'),
        ),
        migrations.AddField(
            model_name='imageinfo',
            name='image_width',
            field=models.IntegerField(default=1, verbose_name='image width'),
        ),
        migrations.AlterField(
            model_name='imageinfo',
            name='annotation_file',
            field=models.CharField(default=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Data.Image', verbose_name='image name'), max_length=50, verbose_name='annotation file'),
        ),
    ]
