# Generated by Django 2.0.13 on 2019-05-10 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0007_auto_20190510_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageinfo',
            name='bndbox_ymax',
            field=models.IntegerField(default=models.IntegerField(default=1, verbose_name='image height'), verbose_name='bndbox yMax'),
        ),
        migrations.AlterField(
            model_name='imageinfo',
            name='bndbox_xmax',
            field=models.IntegerField(default=models.IntegerField(default=1, verbose_name='image width'), verbose_name='bndbox xMax'),
        ),
    ]
