# Generated by Django 2.0.13 on 2019-05-10 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0008_auto_20190510_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageinfo',
            name='bndbox_xmax',
            field=models.IntegerField(default=1, verbose_name='bndbox xMax'),
        ),
        migrations.AlterField(
            model_name='imageinfo',
            name='bndbox_ymax',
            field=models.IntegerField(default=1, verbose_name='bndbox yMax'),
        ),
    ]
