# Generated by Django 2.0.13 on 2019-05-10 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0009_auto_20190510_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageinfo',
            name='image_channels',
            field=models.IntegerField(default=3, verbose_name='image channels'),
        ),
    ]
