# Generated by Django 2.0.13 on 2019-05-10 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0012_auto_20190510_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageinfo',
            name='bndbox_xmax',
        ),
        migrations.RemoveField(
            model_name='imageinfo',
            name='bndbox_xmin',
        ),
        migrations.RemoveField(
            model_name='imageinfo',
            name='bndbox_ymax',
        ),
        migrations.RemoveField(
            model_name='imageinfo',
            name='bndbox_ymin',
        ),
        migrations.RemoveField(
            model_name='imageinfo',
            name='image_channels',
        ),
        migrations.RemoveField(
            model_name='imageinfo',
            name='parents',
        ),
        migrations.RemoveField(
            model_name='imageinfo',
            name='parents_hash',
        ),
    ]
