# Generated by Django 2.0.13 on 2019-05-10 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0013_auto_20190510_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageinfo',
            name='name',
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': 'image info', 'verbose_name_plural': 'image infos'},
        ),
        migrations.DeleteModel(
            name='ImageInfo',
        ),
    ]
