# Generated by Django 2.0.13 on 2019-05-10 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Data', '0015_auto_20190510_1504'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('dataset_name', models.CharField(default='', max_length=50, primary_key=True, serialize=False, verbose_name='dataset name')),
                ('dataset_source', models.URLField(verbose_name='dataset source')),
                ('dataset_host', models.GenericIPAddressField(default='172.16.18.16', protocol='ipv4', verbose_name='dataset host')),
                ('dataset_address', models.CharField(max_length=100, verbose_name='dataset address')),
                ('trainging_images', models.IntegerField(default=0, verbose_name='training images')),
                ('test_images', models.IntegerField(default=0, verbose_name='test images')),
                ('dataset_images', models.IntegerField(default=0, verbose_name='dataset images')),
                ('dataset_category', models.CharField(choices=[('UNCT', 'uncategoried'), ('FACE', 'face recognize'), ('VEHI', 'vehicle recognize'), ('OBJ', 'object recognize')], default='UNCT', max_length=4, verbose_name='dataset category')),
                ('dataset_import_time', models.DateTimeField(auto_now_add=True, verbose_name='dataset import time')),
                ('data_classes', models.IntegerField(default=0, verbose_name='data classes')),
                ('data_labeled', models.BooleanField(default=True, verbose_name='data labeld')),
                ('train_file', models.CharField(default='train.txt', max_length=100, verbose_name='train label file')),
                ('test_file', models.CharField(default='test.txt', max_length=100, verbose_name='test label file')),
                ('val_file', models.CharField(default='val.txt', max_length=100, verbose_name='val label file')),
            ],
            options={
                'verbose_name': 'dataset',
                'verbose_name_plural': 'datasets',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('image_id', models.UUIDField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='', verbose_name='image')),
                ('image_name', models.CharField(max_length=50, verbose_name='image name')),
                ('image_path', models.CharField(max_length=150, verbose_name='image path')),
                ('image_hash', models.CharField(max_length=34, verbose_name='image hash')),
            ],
            options={
                'verbose_name': 'dataset image',
                'verbose_name_plural': 'dataset images',
            },
        ),
        migrations.CreateModel(
            name='ImageInfo',
            fields=[
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Data.Image', verbose_name='image name')),
                ('lable', models.CharField(max_length=50, verbose_name='image label')),
                ('annotation_file', models.CharField(default=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Data.Image', verbose_name='image name'), max_length=50, verbose_name='annotation file')),
                ('image_type', models.CharField(max_length=10, verbose_name='image type')),
                ('image_size', models.CharField(max_length=10, verbose_name='image size')),
                ('image_width', models.IntegerField(default=1, verbose_name='image width')),
                ('image_height', models.IntegerField(default=1, verbose_name='image height')),
                ('color_space', models.CharField(choices=[('sRGB', 'sRGB'), ('AdobeRGB', 'AdobeRGB'), ('AppleRGB', 'AppleRGB'), ('ColorMatchRGB', 'ColorMatchRGB'), ('CMYK', 'CMYK'), ('YIQ', 'YIQ'), ('YUV|YCrCb', 'YUV|YCrCb'), ('HSV', 'HSV'), ('HSI|HSL', 'HSI|HSL'), ('L*a*b', 'L*a*b'), ('CIERGB', 'CIERGB'), ('CIELUV', 'CIELUV'), ('CIELAB', 'CIELAB'), ('CIE1931XYZ', 'CIE1931XYZ'), ('CIE1964UVW', 'CIE1964UVW')], default='sRGB', max_length=10, verbose_name='color space')),
                ('image_resolution', models.CharField(max_length=13, verbose_name='image resolution')),
                ('image_channels', models.IntegerField(default=3, verbose_name='image channels')),
                ('parents', models.CharField(default='', max_length=50, verbose_name='image parents')),
                ('parents_hash', models.CharField(max_length=34, verbose_name='parents hash')),
                ('bndbox_xmin', models.IntegerField(default=1, verbose_name='bndbox xMin')),
                ('bndbox_xmax', models.IntegerField(default=1, verbose_name='bndbox xMax')),
                ('bndbox_ymin', models.IntegerField(default=1, verbose_name='bndbox yMin')),
                ('bndbox_ymax', models.IntegerField(default=1, verbose_name='bndbox yMax')),
            ],
            options={
                'verbose_name': 'image info',
                'verbose_name_plural': 'image infos',
            },
        ),
        migrations.AddField(
            model_name='image',
            name='image_belongto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Data.Dataset'),
        ),
    ]
