# Generated by Django 2.0.13 on 2019-05-10 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0018_auto_20190510_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageinfo',
            name='bndbox_xmax',
            field=models.IntegerField(blank=True, verbose_name='bndbox xMax'),
        ),
        migrations.AlterField(
            model_name='imageinfo',
            name='bndbox_xmin',
            field=models.IntegerField(blank=True, verbose_name='bndbox xMin'),
        ),
        migrations.AlterField(
            model_name='imageinfo',
            name='bndbox_ymax',
            field=models.IntegerField(blank=True, verbose_name='bndbox yMax'),
        ),
        migrations.AlterField(
            model_name='imageinfo',
            name='bndbox_ymin',
            field=models.IntegerField(blank=True, verbose_name='bndbox yMin'),
        ),
        migrations.AlterField(
            model_name='imageinfo',
            name='image_type',
            field=models.CharField(choices=[('JPG|JPEG', 'JPG|JPEG'), ('BMP', 'BMP'), ('PNG', 'PNG')], default='JPG|JPEG', max_length=10, verbose_name='image type'),
        ),
        migrations.AlterField(
            model_name='imageinfo',
            name='parents',
            field=models.CharField(blank=True, max_length=50, verbose_name='image parents'),
        ),
        migrations.AlterField(
            model_name='imageinfo',
            name='parents_hash',
            field=models.CharField(blank=True, max_length=34, verbose_name='parents hash'),
        ),
    ]
