# Generated by Django 2.0.13 on 2019-05-10 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0019_auto_20190510_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageinfo',
            name='bndbox_xmax',
            field=models.IntegerField(blank=True, default=models.IntegerField(default=1, verbose_name='image width'), verbose_name='bndbox xMax'),
        ),
        migrations.AlterField(
            model_name='imageinfo',
            name='bndbox_xmin',
            field=models.IntegerField(blank=True, default=1, verbose_name='bndbox xMin'),
        ),
        migrations.AlterField(
            model_name='imageinfo',
            name='bndbox_ymax',
            field=models.IntegerField(blank=True, default=models.IntegerField(default=1, verbose_name='image height'), verbose_name='bndbox yMax'),
        ),
        migrations.AlterField(
            model_name='imageinfo',
            name='bndbox_ymin',
            field=models.IntegerField(blank=True, default=1, verbose_name='bndbox yMin'),
        ),
    ]
